name: Linting and formatting on PR
on:
  pull_request:
    branches:
      - '**'
    
jobs:

  Continuous-Integration:

    name: Performs linting, formatting on the application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Install Dependencies for frontend
        run: cd frontend && npm install --legacy-peer-deps

      - name: Install Dependencies for backend
        run: cd backend && npm install --legacy-peer-deps

      - name: Run linting check
        run: npm run lint

      - name: Check formatting
        run: npm run format